# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles /app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IPEFTC

# Build rule for target.
IPEFTC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IPEFTC
.PHONY : IPEFTC

# fast build rule for target.
IPEFTC/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/build
.PHONY : IPEFTC/fast

CLIHandler.o: CLIHandler.cpp.o
.PHONY : CLIHandler.o

# target to build an object file
CLIHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/CLIHandler.cpp.o
.PHONY : CLIHandler.cpp.o

CLIHandler.i: CLIHandler.cpp.i
.PHONY : CLIHandler.i

# target to preprocess a source file
CLIHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/CLIHandler.cpp.i
.PHONY : CLIHandler.cpp.i

CLIHandler.s: CLIHandler.cpp.s
.PHONY : CLIHandler.s

# target to generate assembly for a file
CLIHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/CLIHandler.cpp.s
.PHONY : CLIHandler.cpp.s

Config.o: Config.cpp.o
.PHONY : Config.o

# target to build an object file
Config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/Config.cpp.o
.PHONY : Config.cpp.o

Config.i: Config.cpp.i
.PHONY : Config.i

# target to preprocess a source file
Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/Config.cpp.i
.PHONY : Config.cpp.i

Config.s: Config.cpp.s
.PHONY : Config.s

# target to generate assembly for a file
Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/Config.cpp.s
.PHONY : Config.cpp.s

ConfigParser.o: ConfigParser.cpp.o
.PHONY : ConfigParser.o

# target to build an object file
ConfigParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/ConfigParser.cpp.o
.PHONY : ConfigParser.cpp.o

ConfigParser.i: ConfigParser.cpp.i
.PHONY : ConfigParser.i

# target to preprocess a source file
ConfigParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/ConfigParser.cpp.i
.PHONY : ConfigParser.cpp.i

ConfigParser.s: ConfigParser.cpp.s
.PHONY : ConfigParser.s

# target to generate assembly for a file
ConfigParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/ConfigParser.cpp.s
.PHONY : ConfigParser.cpp.s

LinuxAsyncNetworkInterface.o: LinuxAsyncNetworkInterface.cpp.o
.PHONY : LinuxAsyncNetworkInterface.o

# target to build an object file
LinuxAsyncNetworkInterface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/LinuxAsyncNetworkInterface.cpp.o
.PHONY : LinuxAsyncNetworkInterface.cpp.o

LinuxAsyncNetworkInterface.i: LinuxAsyncNetworkInterface.cpp.i
.PHONY : LinuxAsyncNetworkInterface.i

# target to preprocess a source file
LinuxAsyncNetworkInterface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/LinuxAsyncNetworkInterface.cpp.i
.PHONY : LinuxAsyncNetworkInterface.cpp.i

LinuxAsyncNetworkInterface.s: LinuxAsyncNetworkInterface.cpp.s
.PHONY : LinuxAsyncNetworkInterface.s

# target to generate assembly for a file
LinuxAsyncNetworkInterface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/LinuxAsyncNetworkInterface.cpp.s
.PHONY : LinuxAsyncNetworkInterface.cpp.s

Logger.o: Logger.cpp.o
.PHONY : Logger.o

# target to build an object file
Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/Logger.cpp.o
.PHONY : Logger.cpp.o

Logger.i: Logger.cpp.i
.PHONY : Logger.i

# target to preprocess a source file
Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/Logger.cpp.i
.PHONY : Logger.cpp.i

Logger.s: Logger.cpp.s
.PHONY : Logger.s

# target to generate assembly for a file
Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/Logger.cpp.s
.PHONY : Logger.cpp.s

PacketGenerator.o: PacketGenerator.cpp.o
.PHONY : PacketGenerator.o

# target to build an object file
PacketGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/PacketGenerator.cpp.o
.PHONY : PacketGenerator.cpp.o

PacketGenerator.i: PacketGenerator.cpp.i
.PHONY : PacketGenerator.i

# target to preprocess a source file
PacketGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/PacketGenerator.cpp.i
.PHONY : PacketGenerator.cpp.i

PacketGenerator.s: PacketGenerator.cpp.s
.PHONY : PacketGenerator.s

# target to generate assembly for a file
PacketGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/PacketGenerator.cpp.s
.PHONY : PacketGenerator.cpp.s

PacketReceiver.o: PacketReceiver.cpp.o
.PHONY : PacketReceiver.o

# target to build an object file
PacketReceiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/PacketReceiver.cpp.o
.PHONY : PacketReceiver.cpp.o

PacketReceiver.i: PacketReceiver.cpp.i
.PHONY : PacketReceiver.i

# target to preprocess a source file
PacketReceiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/PacketReceiver.cpp.i
.PHONY : PacketReceiver.cpp.i

PacketReceiver.s: PacketReceiver.cpp.s
.PHONY : PacketReceiver.s

# target to generate assembly for a file
PacketReceiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/PacketReceiver.cpp.s
.PHONY : PacketReceiver.cpp.s

TestController.o: TestController.cpp.o
.PHONY : TestController.o

# target to build an object file
TestController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/TestController.cpp.o
.PHONY : TestController.cpp.o

TestController.i: TestController.cpp.i
.PHONY : TestController.i

# target to preprocess a source file
TestController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/TestController.cpp.i
.PHONY : TestController.cpp.i

TestController.s: TestController.cpp.s
.PHONY : TestController.s

# target to generate assembly for a file
TestController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/TestController.cpp.s
.PHONY : TestController.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IPEFTC.dir/build.make CMakeFiles/IPEFTC.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IPEFTC"
	@echo "... CLIHandler.o"
	@echo "... CLIHandler.i"
	@echo "... CLIHandler.s"
	@echo "... Config.o"
	@echo "... Config.i"
	@echo "... Config.s"
	@echo "... ConfigParser.o"
	@echo "... ConfigParser.i"
	@echo "... ConfigParser.s"
	@echo "... LinuxAsyncNetworkInterface.o"
	@echo "... LinuxAsyncNetworkInterface.i"
	@echo "... LinuxAsyncNetworkInterface.s"
	@echo "... Logger.o"
	@echo "... Logger.i"
	@echo "... Logger.s"
	@echo "... PacketGenerator.o"
	@echo "... PacketGenerator.i"
	@echo "... PacketGenerator.s"
	@echo "... PacketReceiver.o"
	@echo "... PacketReceiver.i"
	@echo "... PacketReceiver.s"
	@echo "... TestController.o"
	@echo "... TestController.i"
	@echo "... TestController.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
